name: queezy
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  auto_size_text: ^3.0.0
  flutter_svg: ^1.1.6
  animate_do: ^3.0.2
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

 
  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/Rubik-Medium.ttf
          weight: 600
          style: normal
        - asset: fonts/Rubik-SemiBold.ttf
          weight: 800
          style: normal
        - asset: fonts/Rubik-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/Rubik-Regular.ttf
          weight: 500
          style: normal
